version: "3"

volumes:
  caddy:
  torrent:

services:
  cloudflared:
    image: docker.io/cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    restart: 'unless-stopped'

  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest
    container_name: media-jellyfin
    volumes:
      - /home/jellyfin/config:/config
      - /home/jellyfin/cache:/cache
      - type: bind
        source: /home/jellyfin/media/shows
        target: /media/shows
      - type: bind
        source: /home/jellyfin/media/movies
        target: /media/movies
    devices:
      - /dev/dri/:/dev/dri/
    restart: 'unless-stopped'
    ports:
      - 8096:8096
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.loveand.coffee/
      resources:
        reservations:
          cpus: '2'
          memory: 6G

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: media-qbittorrent
    restart: 'unless-stopped'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    ports:
      - 8080:8080
      - 6881:6881/tcp
      - 6881:6881/udp
    volumes:
      - torrent:/config
      - type: bind
        source: /home/jellyfin/media/downloads
        target: /downloads
      - type: bind
        source: /home/jellyfin/media/movies
        target: /content/movies
      - type: bind
        source: /home/jellyfin/media/shows
        target: /content/shows
      - type: bind
        source: /home/jellyfin/media/torrents
        target: /media/torrents
    deploy:
      resources:
        limits:
          cpus: 25m
          memory: 256M

  # radarr:
  #   container_name: media-radarr
  #   image: ghcr.io/hotio/radarr
  #   restart: 'unless-stopped'
  #   ports:
  #     - "7878:7878"
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - UMASK=002
  #     - TZ=Etc/UTC
  #   volumes:
  #     - /home/jellyfin/radarr/config:/config
  #     - /home/jellyfin/radarr/data:/data
  #     - type: bind
  #       source: /home/jellyfin/media/downloads
  #       target: /downloads
  #     - type: bind
  #       source: /home/jellyfin/media/movies
  #       target: /content/movies
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: 25m
  #         memory: 256M

  # sonarr:
  #   container_name: media-sonarr
  #   image: ghcr.io/hotio/sonarr
  #   restart: 'unless-stopped'
  #   ports:
  #     - "8989:8989"
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - UMASK=002
  #     - TZ=Etc/UTC
  #   volumes:
  #     - /home/jellyfin/sonarr/config:/config
  #     - /home/jellyfin/sonarr/data:/data
  #     - type: bind
  #       source: /home/jellyfin/media/downloads
  #       target: /downloads
  #     - type: bind
  #       source: /home/jellyfin/media/shows
  #       target: /content/shows
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: 25m
  #         memory: 256M

  # jackett:
  #   container_name: media-jackett
  #   image: ghcr.io/hotio/jackett
  #   restart: 'unless-stopped'
  #   ports:
  #     - "9117:9117"
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - UMASK=002
  #     - TZ=Etc/UTC
  #   volumes:
  #     - /home/jellyfin/jackett/config:/config
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: 25m
  #         memory: 256M

  watchtower:
    image: containrrr/watchtower
    container_name: media-watchtower
    restart: 'unless-stopped'
    environment:
      - WATCHTOWER_DEBUG=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 3600 --debug jellyfin caddy
