version: "3"

volumes:
  caddy:
  torrent:

services:
  cloudflared:
    image: docker.io/cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    restart: 'unless-stopped'

  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest
    container_name: media-jellyfin
    volumes:
      - /home/jellyfin/config:/config
      - /home/jellyfin/cache:/cache
      - type: bind
        source: /home/jellyfin/media/shows
        target: /media/shows
      - type: bind
        source: /home/jellyfin/media/movies
        target: /media/movies
    devices:
      - /dev/dri/:/dev/dri/
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.loveand.coffee/

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: media-qbittorrent
    restart: 'unless-stopped'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    ports:
      - 8080:8080
      - 6881:6881/tcp
      - 6881:6881/udp
    volumes:
      - torrent:/config
      - type: bind
        source: /home/jellyfin/media/shows
        target: /downloads
      - type: bind
        source: /home/jellyfin/media/movies
        target: /movies
      - type: bind
        source: /home/jellyfin/media/torrents
        target: /media/torrents

  watchtower:
    image: containrrr/watchtower
    container_name: media-watchtower
    restart: 'unless-stopped'
    environment:
      - WATCHTOWER_DEBUG=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 3600 --debug jellyfin caddy
