volumes:
  torrent:
  movies:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=unas-4.localdomain,nolock,soft,rw"
      device: ":/var/nfs/shared/media/movies"

  shows:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=unas-4.localdomain,nolock,soft,rw"
      device: ":/var/nfs/shared/media/shows"

  torrents:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=unas-4.localdomain,nolock,soft,rw"
      device: ":/var/nfs/shared/torrents"

  downloading:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=unas-4.localdomain,nolock,soft,rw"
      device: ":/var/nfs/shared/downloading"

services:
  cloudflared:
    image: docker.io/cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    restart: 'unless-stopped'

  protonvpn:
    image: docker.io/qmcgaw/gluetun:latest
    container_name: protonvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file: .env
    environment:
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - VPN_PORT_FORWARDING=${VPN_PORT_FORWARDING}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c '/usr/bin/wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:${QBITTORRENT_WEBUI_PORT}/api/v2/app/setPreferences 2>&1'
      - VPN_PORT_FORWARDING_DOWN_COMMAND=/bin/sh -c '/usr/bin/wget -O- --retry-connrefused --post-data "json={\"listen_port\":0,\"current_network_interface\":\"lo\"}" http://127.0.0.1:${QBITTORRENT_WEBUI_PORT}/api/v2/app/setPreferences 2>&1'
    volumes:
      - ./vpn:/gluetun
    ports:
      - ${QBITTORRENT_WEBUI_PORT}:${QBITTORRENT_WEBUI_PORT}
    restart: unless-stopped
    
  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest
    container_name: media-jellyfin
    volumes:
      - /home/jellyfin/config:/config
      - /home/jellyfin/cache:/cache
      - shows:/media/shows
      - movies:/media/movies
    devices:
      - /dev/dri/:/dev/dri/
    restart: 'unless-stopped'
    ports:
      - 8096:8096
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.loveand.coffee/
    deploy:
      resources:
        reservations:
          cpus: "2"
          memory: "6G"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: media-qbittorrent
    restart: 'unless-stopped'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    ports:
      - 8080:8080
      - 6881:6881/tcp
      - 6881:6881/udp
    volumes:
      - torrent:/config
      - movies:/content/movies
      - shows:/content/shows
      - downloading:/downloads
      - torrents:/media/torrents
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: "256M"

  radarr:
    container_name: media-radarr
    image: ghcr.io/hotio/radarr
    restart: 'unless-stopped'
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /home/jellyfin/radarr/config:/config
      - /home/jellyfin/radarr/data:/data
      - downloading:/downloads
      - movies:/content/movies
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: "256M"

  sonarr:
    container_name: media-sonarr
    image: ghcr.io/hotio/sonarr
    restart: 'unless-stopped'
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /home/jellyfin/sonarr/config:/config
      - /home/jellyfin/sonarr/data:/data
      - downloading:/downloads
      - shows:/content/shows
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: "256M"

  jackett:
    container_name: media-jackett
    image: ghcr.io/hotio/jackett
    restart: 'unless-stopped'
    ports:
      - "9117:9117"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /home/jellyfin/jackett/config:/config
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: "256M"

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/jellyfin/ha/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_aa262c124df3ef118184c41b6d9880ab-if00-port0:/dev/ttyUSB0
    environment:
      TZ: Europe/London