apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-08-22T12:48:15Z"
  labels:
    app: media
  name: media
spec:
  containers:
  - name: caddy
    image: ghcr.io/da1rren/caddy:main
    env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: media-secrets
          key: cf-api-token
    ports:
    - containerPort: 80
      hostPort: 80
      protocol: tcp
    - containerPort: 443
      hostPort: 443
      protocol: tcp
    volumeMounts:
    - mountPath: /data
      name: caddy

  - name: jellyfin
    image: docker.io/jellyfin/jellyfin:latest
    volumeMounts:
    - mountPath: /media/movies
      name: movies
    - mountPath: /media/tv
      name: tv
    - mountPath: /config
      name: config
    - mountPath: /cache
      name: cache
    ports:
    - containerPort: 8096
      hostPort: 8096
      protocol: tcp
  volumes:
  - hostPath:
      path: /home/jellyfin/media/movies
      type: Directory
    name: movies
  - hostPath:
      path: /home/jellyfin/media/tv
      type: Directory
    name: tv
  - hostPath:
      path: /home/jellyfin/config
      type: Directory
    name: config
  - hostPath:
      path: /home/jellyfin/cache
      type: Directory
    name: cache
  - persistentVolumeClaim:
      claimName: caddy
    name: caddy
