name: docker-compose-up

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "5 4 * * 1"

jobs:
  update-media-pi:
    runs-on: media
    env:
      TUNNEL_TOKEN: ${{ secrets.TUNNEL_TOKEN }}
      TZ: "Etc/UTC"
      QBITTORRENT_WEBUI_PORT: "8096"
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: openvpn
      OPENVPN_USER: ${{ secrets.OPENVPN_USER }}
      OPENVPN_PASSWORD: ${{ secrets.OPENVPN_PASSWORD }}
      SERVER_COUNTRIES: Netherlands,Germany
      VPN_PORT_FORWARDING: on
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update docker compose
        run: |
          docker compose pull
          docker compose up -d --force-recreate --remove-orphans
