name: docker-compose-up

on:
  push:
    branches:
      - main
  schedule:
    - cron: "5 4 * * 1"

jobs:
  update-media-pi:
    runs-on: media
    env:
      TUNNEL_TOKEN: ${{ secrets.TUNNEL_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update docker compose
        run: |
          docker compose up -d --force-recreate
